name = 'screeps_rl_env.processors_multiagent'

from screeps_rl_env.processors_multiagent.approach import ApproachMultiAgentProcessor
from screeps_rl_env.processors_multiagent.processor import ScreepsMultiAgentProcessor
